[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
uuid = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
tungstenite = "0.26.2"
