[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
uuid = { workspace = true }
tokio-tungstenite = "0.26.2"
tokio = { workspace = true }
futures-util = "0.3.31"
rmp-serde = { workspace = true }
serde = { workspace = true }
